-- List tables
SELECT name FROM sqlite_schema WHERE type='table' ORDER BY name;

-- Show DDL
SELECT name, sql FROM sqlite_schema WHERE type='table' ORDER BY name;

-- Describe columns
PRAGMA table_info('CUSTOMER');
PRAGMA table_info('GUIDE');
PRAGMA table_info('TRIP');
PRAGMA table_info('RESERVATION');
PRAGMA table_info('TRIP_GUIDES');

-- Check foreign keys
PRAGMA foreign_key_list('RESERVATION');
PRAGMA foreign_key_list('TRIP_GUIDES');

-- Verify row counts
SELECT 'CUSTOMER' AS tbl, COUNT(*) FROM CUSTOMER
UNION ALL SELECT 'GUIDE', COUNT(*) FROM GUIDE
UNION ALL SELECT 'TRIP', COUNT(*) FROM TRIP
UNION ALL SELECT 'RESERVATION', COUNT(*) FROM RESERVATION
UNION ALL SELECT 'TRIP_GUIDES', COUNT(*) FROM TRIP_GUIDES;

-- Preview data
SELECT * FROM CUSTOMER ORDER BY CUSTOMER_NUM;
SELECT * FROM GUIDE ORDER BY GUIDE_NUM;
SELECT * FROM TRIP ORDER BY TRIP_ID;
SELECT * FROM RESERVATION ORDER BY RESERVATION_ID;
SELECT * FROM TRIP_GUIDES ORDER BY TRIP_ID, GUIDE_NUM;